import { useMemo } from 'react'

export const useToolsPayload = ({
  accounts,
  accountDrafts,
  setAccountDrafts,
  accountUsage,
  accountError,
  setAccountError,
  accountInput,
  setAccountInput,
  handleRenameAccount,
  handleRemoveAccount,
  handleAddAccount,
  allCategories,
  handleAddCategory,
  handleEditCategory,
  handleDeleteCategory,
  transactions,
  includeDeletedExport,
  setIncludeDeletedExport,
  handleExportJson,
  handleExportCsv,
  handleImportJson,
  importPreview,
  handleApplyImport,
  handleCancelImport,
  importError,
  settings,
  currencyInput,
  currencyError,
  rateStatus,
  rateStatusLabel,
  ratesAsOfLabel,
  benchmarkBaseLabel,
  inputClass,
  handleBaseChange,
  handleAddCurrency,
  setCurrencyInput,
  refreshRates,
  handleRateChange,
  handleRemoveCurrency,
  handlePrivacyExport,
  handleUpdatePrivacyRetention,
  handleClearAllData,
  handleClearOldData,
  restorePoints,
  isLoadingRestorePoints,
  handleCreateRestorePoint,
  handleRestoreFromPoint,
  handleDeleteRestorePoint,
  auditLogs,
  isLoadingAudit,
  autoSyncEnabled,
  syncInterval,
  setAutoSyncEnabled,
  setSyncInterval,
  hasConflicts,
  conflicts,
  handleResolveConflict,
  isResolvingConflict,
}) => {
  const accountsPayload = useMemo(
    () => ({
      accounts,
      accountDrafts,
      setAccountDrafts,
      accountUsage,
      accountError,
      setAccountError,
      accountInput,
      setAccountInput,
      handleRenameAccount,
      handleRemoveAccount,
      handleAddAccount,
    }),
    [
      accounts,
      accountDrafts,
      setAccountDrafts,
      accountUsage,
      accountError,
      setAccountError,
      accountInput,
      setAccountInput,
      handleRenameAccount,
      handleRemoveAccount,
      handleAddAccount,
    ],
  )

  const categoriesPayload = useMemo(
    () => ({
      allCategories,
      handleAddCategory,
      handleEditCategory,
      handleDeleteCategory,
      transactions,
    }),
    [
      allCategories,
      handleAddCategory,
      handleEditCategory,
      handleDeleteCategory,
      transactions,
    ],
  )

  const importPayload = useMemo(
    () => ({
      includeDeletedExport,
      setIncludeDeletedExport,
      handleExportJson,
      handleExportCsv,
      handleImportJson,
      importPreview,
      handleApplyImport,
      handleCancelImport,
      importError,
    }),
    [
      includeDeletedExport,
      setIncludeDeletedExport,
      handleExportJson,
      handleExportCsv,
      handleImportJson,
      importPreview,
      handleApplyImport,
      handleCancelImport,
      importError,
    ],
  )

  const currencyPayload = useMemo(
    () => ({
      settings,
      currencyInput,
      currencyError,
      rateStatus,
      rateStatusLabel,
      ratesAsOfLabel,
      benchmarkBaseLabel,
      inputClass,
      handleBaseChange,
      handleAddCurrency,
      setCurrencyInput,
      refreshRates,
      handleRateChange,
      handleRemoveCurrency,
    }),
    [
      settings,
      currencyInput,
      currencyError,
      rateStatus,
      rateStatusLabel,
      ratesAsOfLabel,
      benchmarkBaseLabel,
      inputClass,
      handleBaseChange,
      handleAddCurrency,
      setCurrencyInput,
      refreshRates,
      handleRateChange,
      handleRemoveCurrency,
    ],
  )

  const privacyPayload = useMemo(
    () => ({
      transactions,
      accounts,
      settings,
      handlePrivacyExport,
      handleUpdatePrivacyRetention,
      handleClearAllData,
      handleClearOldData,
    }),
    [
      transactions,
      accounts,
      settings,
      handlePrivacyExport,
      handleUpdatePrivacyRetention,
      handleClearAllData,
      handleClearOldData,
    ],
  )

  const versioningPayload = useMemo(
    () => ({
      restorePoints,
      isLoadingRestorePoints,
      handleCreateRestorePoint,
      handleRestoreFromPoint,
      handleDeleteRestorePoint,
      auditLogs,
      isLoadingAudit,
    }),
    [
      restorePoints,
      isLoadingRestorePoints,
      handleCreateRestorePoint,
      handleRestoreFromPoint,
      handleDeleteRestorePoint,
      auditLogs,
      isLoadingAudit,
    ],
  )

  const syncPayload = useMemo(
    () => ({
      autoSyncEnabled,
      syncInterval,
      setAutoSyncEnabled,
      setSyncInterval,
      hasConflicts,
      conflicts,
      handleResolveConflict,
      isResolvingConflict,
    }),
    [
      autoSyncEnabled,
      syncInterval,
      setAutoSyncEnabled,
      setSyncInterval,
      hasConflicts,
      conflicts,
      handleResolveConflict,
      isResolvingConflict,
    ],
  )

  return {
    accountsPayload,
    categoriesPayload,
    importPayload,
    currencyPayload,
    privacyPayload,
    versioningPayload,
    syncPayload,
  }
}

export default useToolsPayload
